{% set name = "cdk" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdk/cdk/archive/refs/tags/cdk-{{ version }}.tar.gz
  sha256: 21d832002bdb873521bbb4f1d5a52a1f624212bc30629f02956530e4c6c75af5

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk >=8
    - maven
  run:
    - openjdk >=8

test:
  commands:
    - test -f ${PREFIX}/share/java/cdk.jar  # [not win]
    - test -f ${PREFIX}/share/java/cdk-${PKG_VERSION}.jar  # [not win]
    - test -f %PREFIX%\share\java\cdk.jar  # [win]
    - test -f %PREFIX%\share\java\cdk-%PKG_VERSION%.jar  # [win]

about:
  home: https://github.com/cdk/cdk
  license: LGPL-2.0-only
  license_file:
    - LICENSE
    - aggregate-third-party-report.html

  summary: The CDK is an open-source Java library for cheminformatics and bioinformatics.
  description: |
    Molecule and reaction valence bond representation.
    Read and write file formats: SMILES, SDF, InChI, Mol2, CML, and others.
    Efficient molecule processing algorithms: Ring Finding, Kekulisation, Aromaticity.
    Coordinate generation and rendering.
    Canonical identifiers for fast exact searching.
    Substructure and SMARTS pattern searching.
    ECFP, Daylight, MACCS, and other fingerprint methods for similarity searching.
    QSAR descriptor calculations
  doc_url: https://github.com/cdk/cdk/wiki/Toolkit-Rosetta

extra:
  recipe-maintainers:
    - RJMW
    - jackgisby
